{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.furutuki",
    "module": "transcoder-core",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.16"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-gvt",
          "version": {
            "requires": "1.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "transcoder-core-0.1.0.jar",
          "url": "transcoder-core-0.1.0.jar",
          "size": 56105,
          "sha512": "6be288bd0751caf78308057e28c4051979bf8d18a745b55420c670f759a6964ab067608a15405380d9cd251f7563e6a8e4596d09d901c0e1836b47f0612976f8",
          "sha256": "954826fb3efa3a4ca8344c5143994684294b3616a9658ad51077e2494e05b2c9",
          "sha1": "eedbc9f4aacb6e50f09f8a6786b74aef92c7e0bf",
          "md5": "7afb54d5fbbd6e649bdba056fd6a976a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-bridge",
          "version": {
            "requires": "1.16"
          }
        },
        {
          "group": "org.apache.xmlgraphics",
          "module": "batik-gvt",
          "version": {
            "requires": "1.16"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "transcoder-core-0.1.0.jar",
          "url": "transcoder-core-0.1.0.jar",
          "size": 56105,
          "sha512": "6be288bd0751caf78308057e28c4051979bf8d18a745b55420c670f759a6964ab067608a15405380d9cd251f7563e6a8e4596d09d901c0e1836b47f0612976f8",
          "sha256": "954826fb3efa3a4ca8344c5143994684294b3616a9658ad51077e2494e05b2c9",
          "sha1": "eedbc9f4aacb6e50f09f8a6786b74aef92c7e0bf",
          "md5": "7afb54d5fbbd6e649bdba056fd6a976a"
        }
      ]
    }
  ]
}
